### ISSUE TITLE
util-crypto issue 

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/common#1225]
Hi @jacogr , when build with  "@polkadot/api": "^6.9.1", got this issue: 

``` ts

$ tsc -b
node_modules/@polkadot/util-crypto/base32/bs32.d.ts:26:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.

26 export declare const base32Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@polkadot/util-crypto/base58/bs58.d.ts:21:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.

21 export declare const base58Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@polkadot/util-crypto/base64/bs64.d.ts:26:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.

26 export declare const base64Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by jacogr** [comment]
I'm going to swear... the import is done correctly, `import type { HexString } from '@polkadot/util/types';` (and export is correct as well), will see what can be done so this doesn't happen on compiles.

**Comment by ethernomad** [comment]
There is no src directory in the @polkadot/util package

**Comment by jacogr** [comment]
Yes, I know... and there was no src import in the code either. This is all added by the TS compiler... see the PR for the hack around it - https://github.com/polkadot-js/common/pull/1226
